package com.abelium.inatrace.types;

public enum RequestLogType {
	VISIT_QR,
	VERIFY_BATCH,
	VERIFY_BATCH_ORIGIN,
	CLICK_CERT_STD,
	CLICK_PROD_REC,
	CLICK_COMPANY_PAGE,
	CLICK_SOCIAL_MEDIA,
	LANDING_PAGE,
	CLICK_VERIFY_BATCH,
	CLICK_VERIFY_BATCH_ORIGIN,
}
