package com.abelium.inatrace.components.company.types;

public enum CompanyAction {
	VIEW_COMPANY_PROFILE,
	UPDATE_COMPANY_PROFILE,
	ACTIVATE_COMPANY,
	DEACTIVATE_COMPANY,
	ADD_USER_TO_COMPANY,
	SET_USER_COMPANY_ROLE,
	REMOVE_USER_FROM_COMPANY,
	MERGE_TO_COMPANY
}
