package com.abelium.inatrace.components.user.types;

public enum UserAction {
	VIEW_USER_PROFILE,
	CREATE_COMPANY,
	UPDATE_USER_PROFILE,
	ACTIVATE_USER,
	CONFIRM_USER_EMAIL,
	DEACTIVATE_USER,
	SET_USER_SYSTEM_ADMIN,
	UNSET_USER_SYSTEM_ADMIN,
	SET_USER_REGIONAL_ADMIN,
	UNSET_USER_REGIONAL_ADMIN
}
